### ISSUE TITLE
Possible diff issues

### ISSUE THREAD

**Issue by rainy-me** [alexmacarthur/striff#8]
Hi, I've been finding string diff libraries exactly like this one for a while. Thanks a lot! 

While trying this lib I found the following problem:

Given

```js
const s1 = `
xxx
22
111
`
const s2 = `
xxx
2222
111
`
```

`striff(s1, s2)` will return `{ "removed": [], "added": [] }`. 

Moreover, tweaking the middle line in s2 (e.g `12112222`) will produce many other weird outputs as well.

### Expected behavior

Only if s1 === s2 should both `removed` and `added` be empty?

### Reproduction

https://codesandbox.io/s/proud-frog-0563ni?file=/src/index.js

**Comment by alexmacarthur** [comment]
@rainy-me Thanks for letting me know about this! v1.0.4 addresses it.
